<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SPTDevSuite.Server\SPTDevSuite.Server.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(SptServerAssemblyRoot)' != ''">
    <Reference Include="SemanticVersioning" HintPath="$(SptServerAssemblyRoot)\SemanticVersioning.dll" Private="true" />
    <Reference Include="SPTarkov.Common" HintPath="$(SptServerAssemblyRoot)\SPTarkov.Common.dll" Private="true" />
    <Reference Include="SPTarkov.Server.Core" HintPath="$(SptServerAssemblyRoot)\SPTarkov.Server.Core.dll" Private="true" />
  </ItemGroup>
</Project>
