<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SPTDevSuite.Server</AssemblyName>
    <RootNamespace>SPTDevSuite.Server</RootNamespace>
    <OutputType>Library</OutputType>
    <Version>0.1.0</Version>
    <PackageDirectory>$(MSBuildProjectDirectory)\..\..\Build\SPTDevSuite</PackageDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SPTDevSuite.Contracts\SPTDevSuite.Contracts.csproj" />
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
  </ItemGroup>

  <Target Name="AssembleInstallPackage" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <RemoveDir Directories="$(PackageDirectory)" />
    <MakeDir Directories="$(PackageDirectory)" />
    <Copy SourceFiles="$(TargetPath);$(TargetDir)SPTDevSuite.Contracts.dll" DestinationFolder="$(PackageDirectory)" />
  </Target>
</Project>
